export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SWITCH_TIME_FORMAT = 'SWITCH_TIME_FORMAT';
export const GOOGLE_OAUTH_LOGIN = 'GOOGLE_OAUTH_LOGIN';
export const GOOGLE_OAUTH_LOGOUT = 'GOOGLE_OAUTH_LOGOUT';