const AVAILABILITY_STATUS = Object.freeze({
  CAN_ATTEND: 'CAN_ATTEND',
  BE_LATE: 'BE_LATE',
  LEAVE_EARLY: 'LEAVE_EARLY',
  BE_LATE_LEAVE_EARLY: 'BE_LATE_LEAVE_EARLY',
  CANNOT_ATTEND: 'CANNOT_ATTEND',
});

const REPEAT_FREQ = Object.freeze({
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
});

module.exports = { AVAILABILITY_STATUS, REPEAT_FREQ };