import React from 'react';

import Grid from '@material-ui/core/Grid';

import withSettings from "../HOCs/withSettings";
import RootDialog from "./RootDialog";

const MFADialog = ({
  translate: __, isOpen, qrCode, onClose, onSubmit,
}) => (
  <RootDialog
    isOpen={isOpen}
    onClose={onClose}
    onSubmit={onSubmit}
    submitButtonStyle={{ color: 'red' }}
    submitLabel={__('Disable')}
    closeLabel={__('Close')}
    title={__('Multi-factor authentication activated')}
  >
    <Grid container justifyContent="center">
      <img src={qrCode} alt={__('QR code')}/>
    </Grid>
    {__('To start using it')}:
    <ol>
      <li>{__('Download authenticator app for your phone')} (Google Authenticator, DUO, Microsoft Authenticator, {__('etc')});</li>
      <li>{__('Open the app and scan QR code above')};</li>
      <li>{__('Close this modal')};</li>
      <li>{__('Use autogenerated code from mobile app each time you login into this website')}</li>
    </ol>
  </RootDialog>
);

export default withSettings(MFADialog);
